-- MySQL Script generated by MySQL Workbench
-- 10/16/16 13:04:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pro300
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pro300
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pro300` DEFAULT CHARACTER SET utf8 ;
USE `pro300` ;

-- -----------------------------------------------------
-- Table `pro300`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pro300`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `pro300`.`tb_usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ra` VARCHAR(20) NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` CHAR(20) NULL,
  `perfil` VARCHAR(50) NULL,
  UNIQUE INDEX `tb_usuario_i1` (`email` ASC),
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro300`.`tb_atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pro300`.`tb_atividade` ;

CREATE TABLE IF NOT EXISTS `pro300`.`tb_atividade` (
  `cod_atividade` INT NOT NULL AUTO_INCREMENT,
  `desc_atividade` VARCHAR(500) NOT NULL,
  `token` VARCHAR(100) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `data_encerramento_atv` DATETIME NULL,
  `cod_professor` INT NOT NULL,
  PRIMARY KEY (`cod_atividade`),
  INDEX `tb_atividade_i1` (`cod_professor` ASC),
  INDEX `tb_atividade_i2` (`desc_atividade` ASC),
  INDEX `tb_atividade_i3` (`token` ASC),
  INDEX `tb_atividade_i4` (`data_inicio` ASC, `data_fim` ASC),
  INDEX `tb_atividade_i5` (`data_encerramento_atv` ASC),
  CONSTRAINT `fk_tb_atividade_tb_usuario`
    FOREIGN KEY (`cod_professor`)
    REFERENCES `pro300`.`tb_usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro300`.`tb_inscricao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pro300`.`tb_inscricao` ;

CREATE TABLE IF NOT EXISTS `pro300`.`tb_inscricao` (
  `cod_inscricao` INT NOT NULL AUTO_INCREMENT,
  `p1` DECIMAL NULL,
  `p300` DECIMAL NULL,
  `nota_final` DECIMAL NULL,
  `acrescimo` DECIMAL NULL,
  `grupo` CHAR NULL,
  `data_inscricao` DATETIME NULL,
  `lider` BIT NULL,
  `situacao` INT NULL,
  `cod_aluno` INT NOT NULL,
  `cod_atividade` INT NOT NULL,
  PRIMARY KEY (`cod_inscricao`),
  INDEX `tb_inscricao_i1` (`cod_aluno` ASC),
  INDEX `tb_inscricao_i2` (`cod_atividade` ASC),
  CONSTRAINT `fk_tb_inscricao_tb_usuario1`
    FOREIGN KEY (`cod_aluno`)
    REFERENCES `pro300`.`tb_usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_inscricao_tb_atividade1`
    FOREIGN KEY (`cod_atividade`)
    REFERENCES `pro300`.`tb_atividade` (`cod_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro300`.`tb_avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pro300`.`tb_avaliacao` ;

CREATE TABLE IF NOT EXISTS `pro300`.`tb_avaliacao` (
  `cod_avaliacao` INT NOT NULL AUTO_INCREMENT,
  `cod_inscricao_avaliador` INT NOT NULL,
  `cod_inscricao_avaliado` INT NOT NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`cod_avaliacao`),
  UNIQUE INDEX `tb_avaliacao_i1` (`cod_inscricao_avaliador` ASC, `cod_inscricao_avaliado` ASC),
  INDEX `tb_avaliacao_i2` (`cod_inscricao_avaliado` ASC),
  CONSTRAINT `fk_tb_avaliacao_tb_inscricao1`
    FOREIGN KEY (`cod_inscricao_avaliador`)
    REFERENCES `pro300`.`tb_inscricao` (`cod_inscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_avaliacao_tb_inscricao2`
    FOREIGN KEY (`cod_inscricao_avaliado`)
    REFERENCES `pro300`.`tb_inscricao` (`cod_inscricao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pro300`.`tb_parametro_prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pro300`.`tb_parametro_prova` ;

CREATE TABLE IF NOT EXISTS `pro300`.`tb_parametro_prova` (
  `cod_parametro` INT NOT NULL AUTO_INCREMENT,
  `valor_media_min_melhoria` DECIMAL NOT NULL,
  `valor_media_max_melhoria` DECIMAL NOT NULL,
  `media1` DECIMAL NOT NULL,
  `media2` DECIMAL NOT NULL,
  `media3` DECIMAL NOT NULL,
  `media4` DECIMAL NOT NULL,
  `media5` DECIMAL NOT NULL,
  PRIMARY KEY (`cod_parametro`),
  UNIQUE INDEX `tb_parametro_prova_i1` (`valor_media_min_melhoria` ASC, `valor_media_max_melhoria` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
